version: '3.2'
services:

  postgres:
    container_name: "postgres"
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - log_destination=stderr
      - logging_collector=on
    ports:
      - '5432:5432'
    networks:
      - network
    volumes:
      - ./db/:/var/lib/postgresql/data

  app:
    container_name: "app"
    image: app
    volumes:
      - ./static:/usr/share/nginx/html/static
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    networks:
      - network

  web:
    container_name: "web"
    image: nginx:latest
    depends_on:
      - app
    ports:
      - '80:80'
    networks:
      - network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html/static

networks:
  network:
    driver: bridge

volumes:
  static: